# Generated by Django 4.2.11 on 2025-03-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0002_alter_category_options_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="item_images/"),
        ),
    ]
